#!/bin/sh

BASEDIR=$(pwd)

AUTOLOADS=autoload
BUNDLES=bundle
REPOS=repo

PATHOGEN=pathogen.vim
PATHOGEN_URL=https://raw.github.com/tpope/vim-pathogen/HEAD/autoload/pathogen.vim
SOLARIZED=vim-colors-solarized
SOLARIZED_GIT=https://github.com/altercation/vim-colors-solarized.git
NERDTREE=nerdtree
NERDTREE_GIT=git://github.com/scrooloose/nerdtree.git

MKDIR='mkdir -p'
RM='rm -f'
LN='ln -s'
CLONE='git clone'
UPDATE='git pull'
CURL='curl'
RAKE='rake'

function setup_pathogen()
{
  if [[ -f $AUTOLOADS/$PATHOGEN ]]; then
    echo updating pathogen
  else
    echo installing pathogen
  fi
  $MKDIR $AUTOLOADS
  $CURL -o $AUTOLOADS/$PATHOGEN $PATHOGEN_URL
}

function setup_solarized()
{
  if [[ -d $REPOS/$SOLARIZED ]]; then
    echo updating solarized repo
    cd $REPOS/$SOLARIZED && $UPDATE && cd -
  else
    echo cloning solarized repo
    $CLONE $SOLARIZED_GIT $REPOS/$SOLARIZED
  fi
  $RM $BUNDLES/$SOLARIZED
  $LN ../$REPOS/$SOLARIZED $BUNDLES/$SOLARIZED
}

function setup_nerdtree()
{
  if [[ -d $REPOS/$NERDTREE ]]; then
    echo updating nerdtree repo
    cd $REPOS/$NERDTREE && $UPDATE && cd -
  else
    echo cloning nerdtree repo
    $CLONE $NERDTREE_GIT $REPOS/$NERDTREE
  fi
  cd $REPOS/$NERDTREE && $RAKE install && cd -
}

setup_pathogen
setup_solarized
setup_nerdtree
