#!/bin/sh

BASEDIR=$(pwd)

AUTOLOADS=$BASEDIR/autoload
BUNDLES=$BASEDIR/bundle
REPOS=$BASEDIR/repo

PATHOGEN=pathogen.vim
PATHOGEN_URL=https://raw.github.com/tpope/vim-pathogen/HEAD/autoload/pathogen.vim
SOLARIZED=vim-colors-solarized
SOLARIZED_GIT=https://github.com/altercation/vim-colors-solarized.git
NERDTREE=nerdtree
NERDTREE_GIT=git://github.com/scrooloose/nerdtree.git

MKDIR='mkdir -p'
CLONE='git clone'
UPDATE='git pull'
CURL='curl'
RAKE='rake'

function setup_pathogen()
{
  if [[ -f $AUTOLOADS/$PATHOGEN ]]; then
    echo pathogen already installed
    return
  fi
  echo installing pathogen
  $MKDIR $AUTOLOADS
  $CURL -o $AUTOLOADS/$PATHOGEN $PATHOGEN_URL
}

function setup_solarized()
{
  if [[ -d $BUNDLES/$SOLARIZED ]]; then
    echo solarized already installed
    return
  fi
  echo installing solarized
  $MKDIR $BUNDLES
  $CLONE $SOLARIZED_GIT $BUNDLES/$SOLARIZED
}

function setup_nerdtree()
{
  if [[ -d $REPOS/$NERDTREE ]]; then
    echo updating nerdtree repo
    cd $REPOS/$NERDTREE && $UPDATE && cd -
  else
    echo cloning nerdtree repo
    $CLONE $NERDTREE_GIT $REPOS/$NERDTREE
  fi
  cd $REPOS/$NERDTREE && $RAKE install && cd -
}

setup_pathogen
setup_solarized
setup_nerdtree
