#!/usr/bin/env bash

BASEDIR=$(pwd)

AUTOLOADS=autoload
BUNDLES=bundle
REPOS=repo

PATHOGEN=pathogen.vim
PATHOGEN_URL=https://raw.github.com/tpope/vim-pathogen/HEAD/autoload/$PATHOGEN
SOLARIZED=vim-colors-solarized
SOLARIZED_GIT=https://github.com/altercation/$SOLARIZED.git
NERDTREE=nerdtree
NERDTREE_GIT=https://github.com/scrooloose/$NERDTREE.git
ULTISNIPS=UltiSnips
ULTISNIPS_GIT=https://github.com/vim-scripts/$ULTISNIPS.git

MKDIR='mkdir -p'
RM='rm -f'
LN='ln -s'
CLONE='git clone'
UPDATE='git pull'
CURL='curl'
RAKE='rake'

function setup_pathogen()
{
  if [[ -f $AUTOLOADS/$PATHOGEN ]]; then
    echo updating pathogen
  else
    echo installing pathogen
  fi
  $MKDIR $AUTOLOADS
  $CURL -o $AUTOLOADS/$PATHOGEN $PATHOGEN_URL
}

function setup_solarized()
{
  if [[ -d $REPOS/$SOLARIZED ]]; then
    echo updating solarized repo
    cd $REPOS/$SOLARIZED && $UPDATE && cd -
  else
    echo cloning solarized repo
    $CLONE $SOLARIZED_GIT $REPOS/$SOLARIZED
  fi
  $RM $BUNDLES/$SOLARIZED
  $LN ../$REPOS/$SOLARIZED $BUNDLES/$SOLARIZED
}

function setup_nerdtree()
{
  if [[ -d $REPOS/$NERDTREE ]]; then
    echo updating nerdtree repo
    cd $REPOS/$NERDTREE && $UPDATE && cd -
  else
    echo cloning nerdtree repo
    $CLONE $NERDTREE_GIT $REPOS/$NERDTREE
  fi
  $RM $BUNDLES/$NERDTREE
  $LN ../$REPOS/$NERDTREE $BUNDLES/$NERDTREE
}

function setup_ultisnips()
{
  if [[ -d $REPOS/$ULTISNIPS ]]; then
    echo updating nerdtree repo
    cd $REPOS/$ULTISNIPS && $UPDATE && cd -
  else
    echo cloning nerdtree repo
    $CLONE $ULTISNIPS_GIT $REPOS/$ULTISNIPS
  fi
}

setup_pathogen
setup_solarized
setup_nerdtree
setup_ultisnips
